name: Java CI with Spring Boot, Selenium and JMeter

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip xvfb curl gnupg
        curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-keyring.gpg
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-keyring.gpg] https://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Spring Boot in background
      run: |
        java -Dserver.port=8080 -Dserver.address=0.0.0.0 -jar target/healthtrack-1.0.0.jar &
        echo $! > springboot.pid

    - name: Wait for Spring Boot to be ready
      run: |
        for i in {1..30}; do
          if nc -z localhost 8080; then
            echo "Backend is up!"
            break
          fi
          echo "Waiting for backend..."
          sleep 2
        done

    - name: Run Selenium Test
      env:
        BASE_URL: http://localhost:8080
      run: mvn -Dtest=com.healthtrack.SeleniumTest test

    - name: Install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xzf apache-jmeter-5.5.tgz

    - name: Run JMeter Test
      run: apache-jmeter-5.5/bin/jmeter -n -t jmeter/healthtrack_test.jmx -l jmeter/results.jtl

    - name: SonarQube Scan
      if: success()
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=healthtrack -Dsonar.host.url=https://your-sonarqube-instance.com
