
name: Java CI with Spring Boot, Selenium and JMeter

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: seleniarm/standalone-chromium
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Unit Tests
      run: mvn test

    - name: Run Spring Boot in background
      run: mvn spring-boot:run &
    - name: Wait for backend to be ready
      run: |
        echo "Waiting for localhost:8080..."
        for i in {1..30}; do
          nc -z localhost 8080 && echo "Backend is up!" && break
          echo "Waiting..."
          sleep 2
        done
    - name: Install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xzf apache-jmeter-5.5.tgz

    - name: Run Selenium Tests
      run: mvn -Dtest=com.healthtrack.SeleniumTest test

    - name: Run JMeter test
      run: apache-jmeter-5.5/bin/jmeter -n -t jmeter/healthtrack_test.jmx -l jmeter/results.jtl

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=healthtrack -Dsonar.host.url=https://your-sonarqube-instance.com
